name: Test
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    Test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/action-setup@v6

            - name: Use Node.js 24
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build, type-check and lint
              run: pnpm test
